version: '3'

services:
  app:
    build:
      target: prod
      context: .
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: makespace
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_HOST: mariadb
      PORT: '8080'
      PUBLIC_URL: 'http://localhost:8080'
      SESSION_SECRET: secret
      SMTP_HOST: mailcatcher
      SMTP_PORT: '1025'
      SMTP_USER: ''
      SMTP_PASSWORD: ''
      TOKEN_SECRET: secret
      USE_STUBBED_ADAPTERS: 'true'

  mailcatcher:
    image: sj26/mailcatcher@sha256:1f02ff3bd4fd728837d7ddf768346eebd39e5e2232883c41378c02691378e986
    ports:
      - 1080:1080
